exit on error

diff --git a/mod2mp3 b/mod2mp3
--- a/mod2mp3
+++ b/mod2mp3
@@ -1,6 +1,9 @@
 #!/bin/bash
 # mod2mp3 - converts MOD files to MP3 format, based on FFMPEG
 
+# exit on error
+set -e
+
 if [ -z "$1" ]; then
   echo "Error: please specify a *.mod filename as argument"
   echo "Usage: $0 file.mod"
